// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomdata.proto

package org.wechat.bot;

public final class Roomdata {
  private Roomdata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoomDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.iamteer.RoomData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
     */
    java.util.List<RoomData.RoomMember>
        getMembersList();
    /**
     * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
     */
    RoomData.RoomMember getMembers(int index);
    /**
     * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
     */
    int getMembersCount();
    /**
     * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
     */
    java.util.List<? extends RoomData.RoomMemberOrBuilder>
        getMembersOrBuilderList();
    /**
     * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
     */
    RoomData.RoomMemberOrBuilder getMembersOrBuilder(
        int index);

    /**
     * <code>int32 field_2 = 2;</code>
     * @return The field2.
     */
    int getField2();

    /**
     * <code>int32 field_3 = 3;</code>
     * @return The field3.
     */
    int getField3();

    /**
     * <code>int32 field_4 = 4;</code>
     * @return The field4.
     */
    int getField4();

    /**
     * <code>int32 room_capacity = 5;</code>
     * @return The roomCapacity.
     */
    int getRoomCapacity();

    /**
     * <code>int32 field_6 = 6;</code>
     * @return The field6.
     */
    int getField6();

    /**
     * <code>int64 field_7 = 7 [jstype = JS_STRING];</code>
     * @return The field7.
     */
    long getField7();

    /**
     * <code>int64 field_8 = 8 [jstype = JS_STRING];</code>
     * @return The field8.
     */
    long getField8();
  }
  /**
   * Protobuf type {@code com.iamteer.RoomData}
   */
  public static final class RoomData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.iamteer.RoomData)
      RoomDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomData.newBuilder() to construct.
    private RoomData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomData() {
      members_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoomData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Roomdata.internal_static_com_iamteer_RoomData_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Roomdata.internal_static_com_iamteer_RoomData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RoomData.class, Builder.class);
    }

    public interface RoomMemberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.iamteer.RoomData.RoomMember)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string wxid = 1;</code>
       * @return The wxid.
       */
      String getWxid();
      /**
       * <code>string wxid = 1;</code>
       * @return The bytes for wxid.
       */
      com.google.protobuf.ByteString
          getWxidBytes();

      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      String getName();
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>int32 state = 3;</code>
       * @return The state.
       */
      int getState();
    }
    /**
     * Protobuf type {@code com.iamteer.RoomData.RoomMember}
     */
    public static final class RoomMember extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.iamteer.RoomData.RoomMember)
        RoomMemberOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use RoomMember.newBuilder() to construct.
      private RoomMember(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private RoomMember() {
        wxid_ = "";
        name_ = "";
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new RoomMember();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Roomdata.internal_static_com_iamteer_RoomData_RoomMember_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Roomdata.internal_static_com_iamteer_RoomData_RoomMember_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RoomMember.class, Builder.class);
      }

      public static final int WXID_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile Object wxid_ = "";
      /**
       * <code>string wxid = 1;</code>
       * @return The wxid.
       */
      @Override
      public String getWxid() {
        Object ref = wxid_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          wxid_ = s;
          return s;
        }
      }
      /**
       * <code>string wxid = 1;</code>
       * @return The bytes for wxid.
       */
      @Override
      public com.google.protobuf.ByteString
          getWxidBytes() {
        Object ref = wxid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          wxid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NAME_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      @Override
      public String getName() {
        Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      @Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STATE_FIELD_NUMBER = 3;
      private int state_ = 0;
      /**
       * <code>int32 state = 3;</code>
       * @return The state.
       */
      @Override
      public int getState() {
        return state_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(wxid_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, wxid_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        if (state_ != 0) {
          output.writeInt32(3, state_);
        }
        getUnknownFields().writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(wxid_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, wxid_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        if (state_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, state_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof RoomMember)) {
          return super.equals(obj);
        }
        RoomMember other = (RoomMember) obj;

        if (!getWxid()
            .equals(other.getWxid())) return false;
        if (!getName()
            .equals(other.getName())) return false;
        if (getState()
            != other.getState()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + WXID_FIELD_NUMBER;
        hash = (53 * hash) + getWxid().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static RoomMember parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static RoomMember parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static RoomMember parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static RoomMember parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static RoomMember parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static RoomMember parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static RoomMember parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static RoomMember parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static RoomMember parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static RoomMember parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static RoomMember parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static RoomMember parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(RoomMember prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.iamteer.RoomData.RoomMember}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.iamteer.RoomData.RoomMember)
          RoomMemberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Roomdata.internal_static_com_iamteer_RoomData_RoomMember_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Roomdata.internal_static_com_iamteer_RoomData_RoomMember_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  RoomMember.class, Builder.class);
        }

        // Construct using com.iamteer.Roomdata.RoomData.RoomMember.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          wxid_ = "";
          name_ = "";
          state_ = 0;
          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Roomdata.internal_static_com_iamteer_RoomData_RoomMember_descriptor;
        }

        @Override
        public RoomMember getDefaultInstanceForType() {
          return RoomMember.getDefaultInstance();
        }

        @Override
        public RoomMember build() {
          RoomMember result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public RoomMember buildPartial() {
          RoomMember result = new RoomMember(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(RoomMember result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.wxid_ = wxid_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.name_ = name_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.state_ = state_;
          }
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof RoomMember) {
            return mergeFrom((RoomMember)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(RoomMember other) {
          if (other == RoomMember.getDefaultInstance()) return this;
          if (!other.getWxid().isEmpty()) {
            wxid_ = other.wxid_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          if (other.getState() != 0) {
            setState(other.getState());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  wxid_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 18: {
                  name_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                case 24: {
                  state_ = input.readInt32();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 24
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private Object wxid_ = "";
        /**
         * <code>string wxid = 1;</code>
         * @return The wxid.
         */
        public String getWxid() {
          Object ref = wxid_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            wxid_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string wxid = 1;</code>
         * @return The bytes for wxid.
         */
        public com.google.protobuf.ByteString
            getWxidBytes() {
          Object ref = wxid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            wxid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string wxid = 1;</code>
         * @param value The wxid to set.
         * @return This builder for chaining.
         */
        public Builder setWxid(
            String value) {
          if (value == null) { throw new NullPointerException(); }
          wxid_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string wxid = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearWxid() {
          wxid_ = getDefaultInstance().getWxid();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string wxid = 1;</code>
         * @param value The bytes for wxid to set.
         * @return This builder for chaining.
         */
        public Builder setWxidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          wxid_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private Object name_ = "";
        /**
         * <code>string name = 2;</code>
         * @return The name.
         */
        public String getName() {
          Object ref = name_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
            String value) {
          if (value == null) { throw new NullPointerException(); }
          name_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
          name_ = getDefaultInstance().getName();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          name_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }

        private int state_ ;
        /**
         * <code>int32 state = 3;</code>
         * @return The state.
         */
        @Override
        public int getState() {
          return state_;
        }
        /**
         * <code>int32 state = 3;</code>
         * @param value The state to set.
         * @return This builder for chaining.
         */
        public Builder setState(int value) {

          state_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>int32 state = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearState() {
          bitField0_ = (bitField0_ & ~0x00000004);
          state_ = 0;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.iamteer.RoomData.RoomMember)
      }

      // @@protoc_insertion_point(class_scope:com.iamteer.RoomData.RoomMember)
      private static final RoomMember DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new RoomMember();
      }

      public static RoomMember getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<RoomMember>
          PARSER = new com.google.protobuf.AbstractParser<RoomMember>() {
        @Override
        public RoomMember parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<RoomMember> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<RoomMember> getParserForType() {
        return PARSER;
      }

      @Override
      public RoomMember getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int MEMBERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<RoomMember> members_;
    /**
     * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
     */
    @Override
    public java.util.List<RoomMember> getMembersList() {
      return members_;
    }
    /**
     * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
     */
    @Override
    public java.util.List<? extends RoomMemberOrBuilder>
        getMembersOrBuilderList() {
      return members_;
    }
    /**
     * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
     */
    @Override
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
     */
    @Override
    public RoomMember getMembers(int index) {
      return members_.get(index);
    }
    /**
     * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
     */
    @Override
    public RoomMemberOrBuilder getMembersOrBuilder(
        int index) {
      return members_.get(index);
    }

    public static final int FIELD_2_FIELD_NUMBER = 2;
    private int field2_ = 0;
    /**
     * <code>int32 field_2 = 2;</code>
     * @return The field2.
     */
    @Override
    public int getField2() {
      return field2_;
    }

    public static final int FIELD_3_FIELD_NUMBER = 3;
    private int field3_ = 0;
    /**
     * <code>int32 field_3 = 3;</code>
     * @return The field3.
     */
    @Override
    public int getField3() {
      return field3_;
    }

    public static final int FIELD_4_FIELD_NUMBER = 4;
    private int field4_ = 0;
    /**
     * <code>int32 field_4 = 4;</code>
     * @return The field4.
     */
    @Override
    public int getField4() {
      return field4_;
    }

    public static final int ROOM_CAPACITY_FIELD_NUMBER = 5;
    private int roomCapacity_ = 0;
    /**
     * <code>int32 room_capacity = 5;</code>
     * @return The roomCapacity.
     */
    @Override
    public int getRoomCapacity() {
      return roomCapacity_;
    }

    public static final int FIELD_6_FIELD_NUMBER = 6;
    private int field6_ = 0;
    /**
     * <code>int32 field_6 = 6;</code>
     * @return The field6.
     */
    @Override
    public int getField6() {
      return field6_;
    }

    public static final int FIELD_7_FIELD_NUMBER = 7;
    private long field7_ = 0L;
    /**
     * <code>int64 field_7 = 7 [jstype = JS_STRING];</code>
     * @return The field7.
     */
    @Override
    public long getField7() {
      return field7_;
    }

    public static final int FIELD_8_FIELD_NUMBER = 8;
    private long field8_ = 0L;
    /**
     * <code>int64 field_8 = 8 [jstype = JS_STRING];</code>
     * @return The field8.
     */
    @Override
    public long getField8() {
      return field8_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < members_.size(); i++) {
        output.writeMessage(1, members_.get(i));
      }
      if (field2_ != 0) {
        output.writeInt32(2, field2_);
      }
      if (field3_ != 0) {
        output.writeInt32(3, field3_);
      }
      if (field4_ != 0) {
        output.writeInt32(4, field4_);
      }
      if (roomCapacity_ != 0) {
        output.writeInt32(5, roomCapacity_);
      }
      if (field6_ != 0) {
        output.writeInt32(6, field6_);
      }
      if (field7_ != 0L) {
        output.writeInt64(7, field7_);
      }
      if (field8_ != 0L) {
        output.writeInt64(8, field8_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < members_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, members_.get(i));
      }
      if (field2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, field2_);
      }
      if (field3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, field3_);
      }
      if (field4_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, field4_);
      }
      if (roomCapacity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, roomCapacity_);
      }
      if (field6_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, field6_);
      }
      if (field7_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, field7_);
      }
      if (field8_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, field8_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RoomData)) {
        return super.equals(obj);
      }
      RoomData other = (RoomData) obj;

      if (!getMembersList()
          .equals(other.getMembersList())) return false;
      if (getField2()
          != other.getField2()) return false;
      if (getField3()
          != other.getField3()) return false;
      if (getField4()
          != other.getField4()) return false;
      if (getRoomCapacity()
          != other.getRoomCapacity()) return false;
      if (getField6()
          != other.getField6()) return false;
      if (getField7()
          != other.getField7()) return false;
      if (getField8()
          != other.getField8()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMembersCount() > 0) {
        hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getMembersList().hashCode();
      }
      hash = (37 * hash) + FIELD_2_FIELD_NUMBER;
      hash = (53 * hash) + getField2();
      hash = (37 * hash) + FIELD_3_FIELD_NUMBER;
      hash = (53 * hash) + getField3();
      hash = (37 * hash) + FIELD_4_FIELD_NUMBER;
      hash = (53 * hash) + getField4();
      hash = (37 * hash) + ROOM_CAPACITY_FIELD_NUMBER;
      hash = (53 * hash) + getRoomCapacity();
      hash = (37 * hash) + FIELD_6_FIELD_NUMBER;
      hash = (53 * hash) + getField6();
      hash = (37 * hash) + FIELD_7_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getField7());
      hash = (37 * hash) + FIELD_8_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getField8());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RoomData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoomData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoomData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RoomData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoomData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoomData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RoomData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.iamteer.RoomData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.iamteer.RoomData)
        RoomDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Roomdata.internal_static_com_iamteer_RoomData_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Roomdata.internal_static_com_iamteer_RoomData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RoomData.class, Builder.class);
      }

      // Construct using com.iamteer.Roomdata.RoomData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (membersBuilder_ == null) {
          members_ = java.util.Collections.emptyList();
        } else {
          members_ = null;
          membersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        field2_ = 0;
        field3_ = 0;
        field4_ = 0;
        roomCapacity_ = 0;
        field6_ = 0;
        field7_ = 0L;
        field8_ = 0L;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Roomdata.internal_static_com_iamteer_RoomData_descriptor;
      }

      @Override
      public RoomData getDefaultInstanceForType() {
        return RoomData.getDefaultInstance();
      }

      @Override
      public RoomData build() {
        RoomData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RoomData buildPartial() {
        RoomData result = new RoomData(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(RoomData result) {
        if (membersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            members_ = java.util.Collections.unmodifiableList(members_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.members_ = members_;
        } else {
          result.members_ = membersBuilder_.build();
        }
      }

      private void buildPartial0(RoomData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.field2_ = field2_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.field3_ = field3_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.field4_ = field4_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.roomCapacity_ = roomCapacity_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.field6_ = field6_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.field7_ = field7_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.field8_ = field8_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RoomData) {
          return mergeFrom((RoomData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RoomData other) {
        if (other == RoomData.getDefaultInstance()) return this;
        if (membersBuilder_ == null) {
          if (!other.members_.isEmpty()) {
            if (members_.isEmpty()) {
              members_ = other.members_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMembersIsMutable();
              members_.addAll(other.members_);
            }
            onChanged();
          }
        } else {
          if (!other.members_.isEmpty()) {
            if (membersBuilder_.isEmpty()) {
              membersBuilder_.dispose();
              membersBuilder_ = null;
              members_ = other.members_;
              bitField0_ = (bitField0_ & ~0x00000001);
              membersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMembersFieldBuilder() : null;
            } else {
              membersBuilder_.addAllMessages(other.members_);
            }
          }
        }
        if (other.getField2() != 0) {
          setField2(other.getField2());
        }
        if (other.getField3() != 0) {
          setField3(other.getField3());
        }
        if (other.getField4() != 0) {
          setField4(other.getField4());
        }
        if (other.getRoomCapacity() != 0) {
          setRoomCapacity(other.getRoomCapacity());
        }
        if (other.getField6() != 0) {
          setField6(other.getField6());
        }
        if (other.getField7() != 0L) {
          setField7(other.getField7());
        }
        if (other.getField8() != 0L) {
          setField8(other.getField8());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                RoomMember m =
                    input.readMessage(
                        RoomMember.parser(),
                        extensionRegistry);
                if (membersBuilder_ == null) {
                  ensureMembersIsMutable();
                  members_.add(m);
                } else {
                  membersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 16: {
                field2_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                field3_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                field4_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                roomCapacity_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                field6_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                field7_ = input.readInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                field8_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<RoomMember> members_ =
        java.util.Collections.emptyList();
      private void ensureMembersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          members_ = new java.util.ArrayList<RoomMember>(members_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          RoomMember, RoomMember.Builder, RoomMemberOrBuilder> membersBuilder_;

      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public java.util.List<RoomMember> getMembersList() {
        if (membersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(members_);
        } else {
          return membersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public int getMembersCount() {
        if (membersBuilder_ == null) {
          return members_.size();
        } else {
          return membersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public RoomMember getMembers(int index) {
        if (membersBuilder_ == null) {
          return members_.get(index);
        } else {
          return membersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public Builder setMembers(
          int index, RoomMember value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.set(index, value);
          onChanged();
        } else {
          membersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public Builder setMembers(
          int index, RoomMember.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.set(index, builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public Builder addMembers(RoomMember value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.add(value);
          onChanged();
        } else {
          membersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public Builder addMembers(
          int index, RoomMember value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.add(index, value);
          onChanged();
        } else {
          membersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public Builder addMembers(
          RoomMember.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.add(builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public Builder addMembers(
          int index, RoomMember.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.add(index, builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public Builder addAllMembers(
          Iterable<? extends RoomMember> values) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, members_);
          onChanged();
        } else {
          membersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public Builder clearMembers() {
        if (membersBuilder_ == null) {
          members_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          membersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public Builder removeMembers(int index) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.remove(index);
          onChanged();
        } else {
          membersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public RoomMember.Builder getMembersBuilder(
          int index) {
        return getMembersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public RoomMemberOrBuilder getMembersOrBuilder(
          int index) {
        if (membersBuilder_ == null) {
          return members_.get(index);  } else {
          return membersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public java.util.List<? extends RoomMemberOrBuilder>
           getMembersOrBuilderList() {
        if (membersBuilder_ != null) {
          return membersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(members_);
        }
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public RoomMember.Builder addMembersBuilder() {
        return getMembersFieldBuilder().addBuilder(
            RoomMember.getDefaultInstance());
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public RoomMember.Builder addMembersBuilder(
          int index) {
        return getMembersFieldBuilder().addBuilder(
            index, RoomMember.getDefaultInstance());
      }
      /**
       * <code>repeated .com.iamteer.RoomData.RoomMember members = 1;</code>
       */
      public java.util.List<RoomMember.Builder>
           getMembersBuilderList() {
        return getMembersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          RoomMember, RoomMember.Builder, RoomMemberOrBuilder>
          getMembersFieldBuilder() {
        if (membersBuilder_ == null) {
          membersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              RoomMember, RoomMember.Builder, RoomMemberOrBuilder>(
                  members_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          members_ = null;
        }
        return membersBuilder_;
      }

      private int field2_ ;
      /**
       * <code>int32 field_2 = 2;</code>
       * @return The field2.
       */
      @Override
      public int getField2() {
        return field2_;
      }
      /**
       * <code>int32 field_2 = 2;</code>
       * @param value The field2 to set.
       * @return This builder for chaining.
       */
      public Builder setField2(int value) {

        field2_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field_2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearField2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        field2_ = 0;
        onChanged();
        return this;
      }

      private int field3_ ;
      /**
       * <code>int32 field_3 = 3;</code>
       * @return The field3.
       */
      @Override
      public int getField3() {
        return field3_;
      }
      /**
       * <code>int32 field_3 = 3;</code>
       * @param value The field3 to set.
       * @return This builder for chaining.
       */
      public Builder setField3(int value) {

        field3_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field_3 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearField3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        field3_ = 0;
        onChanged();
        return this;
      }

      private int field4_ ;
      /**
       * <code>int32 field_4 = 4;</code>
       * @return The field4.
       */
      @Override
      public int getField4() {
        return field4_;
      }
      /**
       * <code>int32 field_4 = 4;</code>
       * @param value The field4 to set.
       * @return This builder for chaining.
       */
      public Builder setField4(int value) {

        field4_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field_4 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearField4() {
        bitField0_ = (bitField0_ & ~0x00000008);
        field4_ = 0;
        onChanged();
        return this;
      }

      private int roomCapacity_ ;
      /**
       * <code>int32 room_capacity = 5;</code>
       * @return The roomCapacity.
       */
      @Override
      public int getRoomCapacity() {
        return roomCapacity_;
      }
      /**
       * <code>int32 room_capacity = 5;</code>
       * @param value The roomCapacity to set.
       * @return This builder for chaining.
       */
      public Builder setRoomCapacity(int value) {

        roomCapacity_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 room_capacity = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomCapacity() {
        bitField0_ = (bitField0_ & ~0x00000010);
        roomCapacity_ = 0;
        onChanged();
        return this;
      }

      private int field6_ ;
      /**
       * <code>int32 field_6 = 6;</code>
       * @return The field6.
       */
      @Override
      public int getField6() {
        return field6_;
      }
      /**
       * <code>int32 field_6 = 6;</code>
       * @param value The field6 to set.
       * @return This builder for chaining.
       */
      public Builder setField6(int value) {

        field6_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field_6 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearField6() {
        bitField0_ = (bitField0_ & ~0x00000020);
        field6_ = 0;
        onChanged();
        return this;
      }

      private long field7_ ;
      /**
       * <code>int64 field_7 = 7 [jstype = JS_STRING];</code>
       * @return The field7.
       */
      @Override
      public long getField7() {
        return field7_;
      }
      /**
       * <code>int64 field_7 = 7 [jstype = JS_STRING];</code>
       * @param value The field7 to set.
       * @return This builder for chaining.
       */
      public Builder setField7(long value) {

        field7_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int64 field_7 = 7 [jstype = JS_STRING];</code>
       * @return This builder for chaining.
       */
      public Builder clearField7() {
        bitField0_ = (bitField0_ & ~0x00000040);
        field7_ = 0L;
        onChanged();
        return this;
      }

      private long field8_ ;
      /**
       * <code>int64 field_8 = 8 [jstype = JS_STRING];</code>
       * @return The field8.
       */
      @Override
      public long getField8() {
        return field8_;
      }
      /**
       * <code>int64 field_8 = 8 [jstype = JS_STRING];</code>
       * @param value The field8 to set.
       * @return This builder for chaining.
       */
      public Builder setField8(long value) {

        field8_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int64 field_8 = 8 [jstype = JS_STRING];</code>
       * @return This builder for chaining.
       */
      public Builder clearField8() {
        bitField0_ = (bitField0_ & ~0x00000080);
        field8_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.iamteer.RoomData)
    }

    // @@protoc_insertion_point(class_scope:com.iamteer.RoomData)
    private static final RoomData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RoomData();
    }

    public static RoomData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomData>
        PARSER = new com.google.protobuf.AbstractParser<RoomData>() {
      @Override
      public RoomData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RoomData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RoomData> getParserForType() {
      return PARSER;
    }

    @Override
    public RoomData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iamteer_RoomData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iamteer_RoomData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iamteer_RoomData_RoomMember_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iamteer_RoomData_RoomMember_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016roomdata.proto\022\013com.iamteer\"\373\001\n\010RoomDa" +
      "ta\0221\n\007members\030\001 \003(\0132 .com.iamteer.RoomDa" +
      "ta.RoomMember\022\017\n\007field_2\030\002 \001(\005\022\017\n\007field_" +
      "3\030\003 \001(\005\022\017\n\007field_4\030\004 \001(\005\022\025\n\rroom_capacit" +
      "y\030\005 \001(\005\022\017\n\007field_6\030\006 \001(\005\022\023\n\007field_7\030\007 \001(" +
      "\003B\0020\001\022\023\n\007field_8\030\010 \001(\003B\0020\001\0327\n\nRoomMember" +
      "\022\014\n\004wxid\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005state\030\003 " +
      "\001(\005B\014Z\n./;wcferryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_iamteer_RoomData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iamteer_RoomData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iamteer_RoomData_descriptor,
        new String[] { "Members", "Field2", "Field3", "Field4", "RoomCapacity", "Field6", "Field7", "Field8", });
    internal_static_com_iamteer_RoomData_RoomMember_descriptor =
      internal_static_com_iamteer_RoomData_descriptor.getNestedTypes().get(0);
    internal_static_com_iamteer_RoomData_RoomMember_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iamteer_RoomData_RoomMember_descriptor,
        new String[] { "Wxid", "Name", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
